export type TimelineCategory = 'job' | 'education' | 'project';

export interface TimelineEntry {
  category: TimelineCategory;
  // 'card' renders a TimelineCard, 'project' renders a TimelineProjectCard
  kind: 'card' | 'project';
  time: string;
  header: string;
  subheader?: string;
  desc: string;
  tags: string[];
  additional: string;
  link: string;
  icon?: string;
  href?: string;
  // Optional narrative text shown above the card
  note?: string;
}

export const timelineEntries: TimelineEntry[] = [
  {
    category: 'education',
    kind: 'card',
    time: 'October 2025 - October 2027',
    header: 'Technical University of Munich',
    subheader: 'MSc Computer Science',
    desc: 'Continuing my studies with a focus on software engineering and AI.',
    tags: ['Computer Science'],
    additional: '',
    link: '',
  },
  {
    category: 'project',
    kind: 'project',
    time: 'February 2025',
    header: 'BonnyAI',
    desc: 'An AI Agent that can access MongoDB queries to fetch performance data of over 20 E-Commerce marketplace. Enables ease of financial report and pinpoints bad performance accurately. Also enables chatting with the AI via Telegram.',
    tags: [
      'LLM',
      'MongoDB',
      'Database Optimization',
      'Data processing',
      'Telegram Integration',
      'Flask Python',
      'Vue',
    ],
    additional: '',
    href: '/images/bonny.png',
    link: '',
  },
  {
    category: 'job',
    kind: 'card',
    time: 'November 2024 - Present',
    header: 'Infineon Technologies',
    icon: '/images/infineon.png',
    subheader: 'Software Developer',
    desc: 'I develop automations for product simulations and dashboards, including 2D and 3D visualization of products, in constant collaboration with stakeholders on project requirements.',
    tags: ['Vue', 'Node JS', 'Tailwind CSS', 'Typescript', 'REST API', 'Three JS'],
    additional: '',
    link: '',
  },
  {
    category: 'project',
    kind: 'project',
    time: 'October 2024',
    header: 'Temu Bisnis Indonesia',
    desc: 'A web application platform for selling and buying businesses.',
    tags: ['Vue.js', 'Tailwind', 'Typescript', 'Flask Python', 'MongoDB'],
    additional: 'See Project →',
    href: '/images/temu-bisnis.png',
    link: 'https://temubisnis.com',
  },
  {
    category: 'job',
    kind: 'card',
    time: 'October 2023 - October 2024',
    header: 'Agile Robots AG',
    icon: '/images/AGSE.jpeg',
    subheader: 'Software Developer',
    desc: 'I developed a robot solutions interface, collaborating with the design and back-end team.',
    tags: ['Vue', 'GraphQL', 'SCSS', 'Typescript'],
    additional: '',
    link: '',
  },
  {
    category: 'job',
    kind: 'card',
    time: 'October 2023 - March 2024',
    icon: '/images/tumai.jpg',
    header: 'TUM.ai Student Initiative',
    subheader: 'Software Developer',
    desc: "Developed TUM.ai's solution for member management and collaboration software platform.",
    tags: ['Software Development', 'Collaboration Platform'],
    additional: '',
    link: '',
  },
  {
    category: 'project',
    kind: 'project',
    time: '2023 - now',
    header: 'PodoMore',
    desc: 'A web application to support the Podomoro studying technique, written in Vue.js.',
    tags: ['Vue.js', 'CSS', 'Typescript'],
    additional: 'See Project →',
    href: '/images/project.webp',
    link: 'https://podomore-one.vercel.app/',
    note:
      'Project-based learning is my favorite way to learn new tools and frameworks. When i was starting to learn Vue.js, I decided to rewrite a past project of mine, Podomore app, in Vue.js.',
  },
  {
    category: 'project',
    kind: 'project',
    time: '2023',
    header: 'PodoMore',
    desc: 'A web application to support the Podomoro studying technique.',
    tags: ['Next.js', 'React.js', 'Tailwind', 'JS'],
    additional: 'See Project →',
    href: '/images/productivity.webp',
    link: 'https://productivity-app-1v2h.vercel.app/',
  },
  {
    category: 'project',
    kind: 'project',
    time: '2023',
    header: 'Artist Concert Tracker',
    desc: "A web application to track artists' upcoming concerts and ticket offers.",
    tags: ['Next.js', 'Tailwind', 'MongoDB', 'API', 'Web Scrapping'],
    additional: 'See Project →',
    href: '/images/artist-tracker.webp',
    link: 'https://github.com/brebribre/artist-concert-tracker',
  },
  {
    category: 'education',
    kind: 'card',
    time: '2023',
    icon: '/images/udemy.png',
    header: 'The Complete 2023 Web Development Bootcamp',
    subheader: 'Udemy, by Angela Yu',
    desc: 'Gives in depth course on Full-Stack Web Development.',
    tags: ['Node', 'React', 'MongoDB', 'SQL'],
    additional: 'See Certificate →',
    link: 'https://www.udemy.com/certificate/UC-1878d032-091d-47ca-b0d5-f72d6c71b488/',
  },
  {
    category: 'job',
    kind: 'card',
    time: 'April 2023 - September 2023',
    icon: '/images/tumai.jpg',
    header: 'TUM.ai Student Initiative',
    subheader: 'Taskforce Recruitment',
    desc: 'Project leader for the TUM.ai Newsletter, including curating content and utilizing Mailchimp. Part of the Recruitment taskforce responsible for planning the recruitment process.',
    tags: ['Mailchimp', 'Recruitment', 'Canva'],
    additional: '',
    link: '',
    note:
      'My time at TUM motivated me to meet new people with the same field of interests as me, which led me to join one of the biggest student initiative in Germany concerning AI.',
  },
  {
    category: 'education',
    kind: 'card',
    time: '2021',
    icon: '/images/edx.png',
    header: 'Object Oriented Programming Course',
    subheader: 'by edX',
    desc: 'Course on Object Oriented Programming, taught using Java.',
    tags: ['Java', 'OOP'],
    additional: 'See Certificate →',
    link: 'https://courses.edx.org/certificates/13a1e14438e24b1cbef45688db0567b5',
  },
  {
    category: 'education',
    kind: 'card',
    time: 'November 2021 - August 2025',
    header: 'Technical University of Munich',
    subheader: 'BSc Computer Science',
    desc: 'With application subject in business administration.',
    tags: ['SQL', 'Java', 'C', 'OOP'],
    additional: '',
    link: '',
  },
  {
    category: 'job',
    kind: 'card',
    time: 'March 2021 - December 2021',
    header: 'PT. Cahaya Optima Karya',
    subheader: 'Frontend Web Developer',
    desc: 'Developed and maintained all the product portfolio websites of the company.',
    tags: ['HTML', 'CSS', 'Javascript', 'Bootstrap'],
    additional: '',
    link: '',
    note:
      'With the rise of remote jobs, i applied and started working as a web developer intern in Jakarta.',
  },
  {
    category: 'education',
    kind: 'card',
    time: 'March 2021 - July 2021',
    header: 'Hochschule Kaiserslautern',
    subheader: 'Studienkolleg (T-Kurs)',
    desc: 'University preparation course for technical degree programs in Germany.',
    tags: ['German', 'Mathematics', 'Physics'],
    additional: '',
    link: '',
  },
  {
    category: 'project',
    kind: 'project',
    time: '2021',
    href: '/images/covid.webp',
    header: 'Indonesia Covid tracker',
    desc: 'Tracks growth of Covid-19 in Indonesia and other countries.',
    tags: ['HTML', 'CSS', 'JS', 'API'],
    link: 'https://github.com/brebribre/Covid-Tracker',
    additional: 'Visit Repository →',
    note:
      'My web development starts here. Starting with simple HTML and CSS projects and learning purely from the internet, i created my first project: A Covid-19 tracker.',
  },
  {
    category: 'education',
    kind: 'card',
    time: '2017 - 2020',
    header: 'SMAK 1 PENABUR Jakarta',
    subheader: 'Natural Sciences, High School in Jakarta, Indonesia',
    desc: 'Equipment and logistics coordinator for one of the most prestigious high school event in Jakarta.',
    tags: ['Leadership', 'Project Management'],
    additional: '',
    link: '',
  },
];
